### ISSUE TITLE
Uncaught Error: Can't work without 'simple-uploader' module

### ISSUE THREAD

**Issue by vincentjiang** [mycolorway/simple-uploader#4]
我已经引入了uploader.js

![image](https://cloud.githubusercontent.com/assets/3729371/9966735/14f87986-5e71-11e5-8f10-bb6593b8f9a3.png)

为什么会报这个错？
![image](https://cloud.githubusercontent.com/assets/3729371/9966749/29ef93f6-5e71-11e5-812b-670b1bafdd89.png)

**Comment by farthinker** [comment]
有没有更多的调试信息，比如这个错误是在哪个文件哪一行出现的

**Comment by vincentjiang** [comment]
![image](https://cloud.githubusercontent.com/assets/3729371/10075760/26e9eed4-630a-11e5-95c7-8c2b8a6645f6.png)

![image](https://cloud.githubusercontent.com/assets/3729371/10075730/f0ba4ba6-6309-11e5-9068-1d835182a6b4.png)

**Comment by zh-h** [comment]
```javascript
Can't work without 'simple-uploader' module
//同样的问题
````
